######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/BGSA_Logo_small_top.png"
logo_on_black: "/img/BGSA_Logo_Transparent.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/BGSA-Carleton-University"
  instagram: "https://www.instagram.com/bgsa_carleton/"
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
# show_search: true
